// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9NTYCxCYuBP0Qy03-6RF21ulek2jxMJg',
    appId: '1:402237592218:web:8037d5716e04cc94cb4523',
    messagingSenderId: '402237592218',
    projectId: 'sueats-82f9b',
    authDomain: 'sueats-82f9b.firebaseapp.com',
    storageBucket: 'sueats-82f9b.firebasestorage.app',
    measurementId: 'G-HPY5ML0NC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA25INHLDO4rNXxaES9W63tZ1hz9qscBU4',
    appId: '1:402237592218:android:d8b8c42c5c142fefcb4523',
    messagingSenderId: '402237592218',
    projectId: 'sueats-82f9b',
    storageBucket: 'sueats-82f9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC-qfmdGFh3oy_En-y-GcAoKxsx3VXk9A',
    appId: '1:402237592218:ios:35c689324525d65fcb4523',
    messagingSenderId: '402237592218',
    projectId: 'sueats-82f9b',
    storageBucket: 'sueats-82f9b.firebasestorage.app',
    iosBundleId: 'com.example.sueatssss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC-qfmdGFh3oy_En-y-GcAoKxsx3VXk9A',
    appId: '1:402237592218:ios:35c689324525d65fcb4523',
    messagingSenderId: '402237592218',
    projectId: 'sueats-82f9b',
    storageBucket: 'sueats-82f9b.firebasestorage.app',
    iosBundleId: 'com.example.sueatssss',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9NTYCxCYuBP0Qy03-6RF21ulek2jxMJg',
    appId: '1:402237592218:web:c76011e7eec75c8dcb4523',
    messagingSenderId: '402237592218',
    projectId: 'sueats-82f9b',
    authDomain: 'sueats-82f9b.firebaseapp.com',
    storageBucket: 'sueats-82f9b.firebasestorage.app',
    measurementId: 'G-FHBD7ZN1B8',
  );
}
